# Generated by Django 5.0.6 on 2024-08-23 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elearning_platform', '0002_rename_user_enrollment_creator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='user',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='creator',
            new_name='student',
        ),
    ]
