# Generated by Django 5.0.6 on 2024-08-23 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning_platform', '0003_rename_user_course_creator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='material_path',
            field=models.FileField(upload_to='materials/'),
        ),
    ]
